require("core.options")
require("core.lazy")
require("core.keymaps")

require("plugins.telescope")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.autocmp")
require("plugins.theme")
require("plugins.icons")
require("plugins.lualine")
require("plugins.autopairs")
require("plugins.dap")
require("plugins.formatting")
require("plugins.extra")
require("plugins.gitsigns")
